[package]
name = "nemscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
duckdb = { version = "1.2.2", default-features = false}
reqwest = { version = "0.11", features = ["rustls-tls", "cookies", "blocking"] }
scraper = "0.14"
url = "2.2"
anyhow = "1.0"
rand = "0.8"
tempfile = "3"
csv = "1.3.1"
zip = "3.0.0"
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"
regex = "1.11.1"
