[package]
name = "nemscraper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

# ---------- Networking stack ----------
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "gzip",
    "rustls-tls",
    "cookies",
    "blocking",
] }

reqwest-middleware = "0.4.2" # <- no extra features here
# -------------------------------------

scraper = "0.14"
url = "2.2"
anyhow = "1.0"
rand = "0.8"
tempfile = "3"
csv = "1.3.1"
zip = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.41"
regex = "1.11.1"
futures = "0.3.31"
async-trait = "0.1.88"
http = "1.3.1"
duckdb = { version = "1.2.2", default-features = false }
