
services:
  grafana:
    image: grafana/grafana:12.0.1-ubuntu
    restart: always
    ports:
      - "3000:3000"
    user: "1000:1000"               
    volumes:
      - assets:/data                   
      - ./grafana/plugins/motherduck-duckdb-datasource:/var/lib/grafana/plugins/motherduck-duckdb-datasource
      - ./grafana/dashboards:/etc/grafana/provisioned_dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "motherduck-duckdb-datasource"

  nemscraper:
    build:
      context: .
      dockerfile: Dockerfile.nemscraper
    working_dir: /usr/src/app
    user: "1000:1000"               
    volumes:
      - assets:/usr/src/app/assets      
    command: ["./target/release/nemscraper"]

volumes:
  assets:
    driver: local
    driver_opts:
      # bind the host’s ./assets folder into a named volume called “assets”
      type: "none"
      o: "bind"
      device: "${PWD}/assets"
