apiVersion: 1

datasources:
  - name: 'nem'                     # A unique name for your data source in Grafana
    type: 'motherduck-duckdb-datasource'      # This MUST be the exact plugin ID.
                                              # This is likely the ID given your previous settings.
    access: proxy                             # 'proxy' (Grafana backend makes requests) or 'direct' (browser makes requests).

    jsonData:
      path: '' # IMPORTANT: Path to your DuckDB file *inside the container*.
